// Copyright 2013 IntelliFactory
//
// Licensed under the Apache License, Version 2.0 (the "License"); you
// may not use this file except in compliance with the License.  You may
// obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied.  See the License for the specific language governing
// permissions and limitations under the License

namespace IntelliFactory.Build

open System
open System.IO
open IntelliFactory.Core
open IntelliFactory.Build

/// Represents a file that is to become a part of a `NuGet` archive.
type INuGetFile =

    /// Reads the file contents.
    abstract Read : unit -> Stream

    /// Relative path inside the NuGet package archive, such as `/lib/net40/My.dll`.
    abstract TargetPath : string

/// A project that contirbutes files to a created NuGet package.
type INuGetExportingProject =

    /// Files exported by the project.
    abstract NuGetFiles : seq<INuGetFile>

/// Represents a reference to the NuGet repository.
type INuGetReference =

    /// The identifier, such as "NuGet.Core".
    abstract PackageId : string

    /// The version, or "None" to obtain latest, such as "2.7.1-alpha".
    abstract PackageVersion : option<string>

    /// The specific paths to reference inside the package archive.
    /// If "None", this is determined automatically.
    abstract Paths : option<seq<string>>

/// Represents a project that can be used as a reference.
type IReferenceProject =

    /// Paths to the assembly files generated by the project.
    abstract GeneratedAssemblyFiles : seq<string>

/// Represents assembly references.
type Reference =
    internal
    | FileRef of string
    | NuGetRef of INuGetReference
    | ProjectRef of IReferenceProject
    | SystemRef of string

    /// Builds a reference to a specific file.
    static member File(filePath: string) = FileRef filePath

    /// Builds a reference to NuGet-supplied artifacts.
    static member NuGet(nuget) = NuGetRef nuget

    /// Builds a reference to project output artifacts.
    static member Project(project: IReferenceProject) = ProjectRef project

    /// Builds a reference to a system-resolved assembly by name.
    static member System(assemblyName: string) = SystemRef assemblyName

/// Represents a project that can build some artifacts.
type IProject =

    /// Builds the project.
    abstract Build : unit -> unit

    /// Cleans the project.
    abstract Clean : unit -> unit

    /// The target framework.
    abstract Framework : Framework

    /// Informational project name.
    abstract Name : string

    /// The references required to build the project.
    abstract References : seq<Reference>

